export const FETCH_MEAL_CATEGORIES_REQUEST = "FETCH_MEAL_CATEGORIES_REQUEST"
export const FETCH_MEAL_CATEGORIES_SUCCESS = "FETCH_MEAL_CATEGORIES_SUCCESS"
export const FETCH_MEAL_CATEGORIES_FAILURE = "FETCH_MEAL_CATEGORIES_FAILURE"

export const FETCH_MEALS_BY_CATEGORY_REQUEST = "FETCH_MEALS_BY_CATEGORY_REQUEST"
export const FETCH_MEALS_BY_CATEGORY_SUCCESS = "FETCH_MEALS_BY_CATEGORY_SUCCESS"
export const FETCH_MEALS_BY_CATEGORY_FAILURE = "FETCH_MEALS_BY_CATEGORY_FAILURE"

export const FETCH_MEAL_REQUEST = "FETCH_MEAL_REQUEST"
export const FETCH_MEAL_SUCCESS = "FETCH_MEAL_SUCCESS"
export const FETCH_MEAL_FAILURE = "FETCH_MEAL_FAILURE"